[package]
name = "simple-embedding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generative-ai = {path = "../../generative-ai"}
tokio = { workspace = true }
dotenv = { workspace = true }
